apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clair-hacbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clair-hacbs
    app.kubernetes.io/part-of: myawesomeapp
  name: clair-hacbs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: clair-hacbs
status:
  loadBalancer: {}
